"""01_initial_schema_baseline

Revision ID: 01145485c28e
Revises: 
Create Date: 2026-08-07 22:41:52.903069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '01145485c28e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions + schemas are not emitted by autogenerate; add explicitly so a
    # fresh database can be fully provisioned via `alembic upgrade head`.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    for schema in ("shared", "aquavision", "crop", "geo", "system"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_thresholds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('threshold_name', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threshold_name'),
    schema='aquavision'
    )
    op.create_table('crop_models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('crop_type', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='crop'
    )
    op.create_table('system_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_successful_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='geo'
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='shared'
    )
    op.create_table('regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('parent_region_id', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='shared'
    )
    op.create_index('idx_regions_geom', 'regions', ['geom'], unique=False, schema='shared', postgresql_using='gist')
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='shared'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='shared'
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_name', sa.Text(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('season', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_table('water_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('wai_score', sa.Numeric(), nullable=True),
    sa.Column('rainfall_anomaly', sa.Numeric(), nullable=True),
    sa.Column('et_anomaly', sa.Numeric(), nullable=True),
    sa.Column('surface_water_change_pct', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aquavision'
    )
    op.create_table('water_indicators_weekly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('surface_water_area_km2', sa.Numeric(), nullable=True),
    sa.Column('surface_water_change_pct', sa.Numeric(), nullable=True),
    sa.Column('rainfall_mm_30day', sa.Numeric(), nullable=True),
    sa.Column('rainfall_anomaly', sa.Numeric(), nullable=True),
    sa.Column('et_mm_8day', sa.Numeric(), nullable=True),
    sa.Column('et_anomaly', sa.Numeric(), nullable=True),
    sa.Column('wai_score', sa.Numeric(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('data_source_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'week_start_date', name='uq_water_indicator_region_week'),
    schema='aquavision'
    )
    op.create_table('water_predictions_weekly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('target_week_start_date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('predicted_severity', sa.Text(), nullable=True),
    sa.Column('predicted_wai_score', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'target_week_start_date', 'model_version', name='uq_water_prediction_region_week_version'),
    schema='aquavision'
    )
    op.create_table('water_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('generated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aquavision'
    )
    op.create_table('crop_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_type', sa.Text(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('risk_category', sa.Text(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crop'
    )
    op.create_table('crop_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_type', sa.Text(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('feature_date', sa.Date(), nullable=False),
    sa.Column('ndvi', sa.Numeric(), nullable=True),
    sa.Column('evi', sa.Numeric(), nullable=True),
    sa.Column('savi', sa.Numeric(), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(), nullable=True),
    sa.Column('temperature_avg', sa.Numeric(), nullable=True),
    sa.Column('soil_moisture', sa.Numeric(), nullable=True),
    sa.Column('wai_score', sa.Numeric(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crop'
    )
    op.create_table('crop_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_type', sa.Text(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('predicted_yield', sa.Numeric(), nullable=False),
    sa.Column('yield_unit', sa.Text(), nullable=False),
    sa.Column('risk_category', sa.Text(), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['crop.crop_models.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crop'
    )
    op.create_table('crop_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('generated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['shared.users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crop'
    )
    op.create_table('geo_overlays',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('wai_score', sa.Numeric(), nullable=True),
    sa.Column('water_severity', sa.Text(), nullable=True),
    sa.Column('predicted_yield', sa.Numeric(), nullable=True),
    sa.Column('yield_risk', sa.Text(), nullable=True),
    sa.Column('combined_risk_score', sa.Numeric(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='geo'
    )
    op.create_index('idx_geo_overlays_geom', 'geo_overlays', ['geom'], unique=False, schema='geo', postgresql_using='gist')
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shared'
    )
    op.create_index('idx_assets_geom', 'assets', ['geom'], unique=False, schema='shared', postgresql_using='gist')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['shared.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['shared.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='shared'
    )
    op.create_table('user_region_scopes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['shared.regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'region_id'),
    schema='shared'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['shared.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='shared'
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['shared.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs', schema='system')
    op.drop_table('user_roles', schema='shared')
    op.drop_table('user_region_scopes', schema='shared')
    op.drop_table('role_permissions', schema='shared')
    op.drop_index('idx_assets_geom', table_name='assets', schema='shared', postgresql_using='gist')
    op.drop_table('assets', schema='shared')
    op.drop_index('idx_geo_overlays_geom', table_name='geo_overlays', schema='geo', postgresql_using='gist')
    op.drop_table('geo_overlays', schema='geo')
    op.drop_table('crop_reports', schema='crop')
    op.drop_table('crop_predictions', schema='crop')
    op.drop_table('crop_features', schema='crop')
    op.drop_table('crop_alerts', schema='crop')
    op.drop_table('water_reports', schema='aquavision')
    op.drop_table('water_predictions_weekly', schema='aquavision')
    op.drop_table('water_indicators_weekly', schema='aquavision')
    op.drop_table('water_alerts', schema='aquavision')
    op.drop_table('pipeline_runs', schema='system')
    op.drop_table('users', schema='shared')
    op.drop_table('roles', schema='shared')
    op.drop_index('idx_regions_geom', table_name='regions', schema='shared', postgresql_using='gist')
    op.drop_table('regions', schema='shared')
    op.drop_table('permissions', schema='shared')
    op.drop_table('system_status', schema='geo')
    op.drop_table('crop_models', schema='crop')
    op.drop_table('water_thresholds', schema='aquavision')
    # ### end Alembic commands ###
    for schema in ("system", "crop", "geo", "aquavision", "shared"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
