// packages/dashboard/src/app/water/alerts/page.tsx
// AquaVision Alerts - review, acknowledge, resolve.
'use client'

import { useState } from 'react'
import { Bell, CheckCircle2, AlertTriangle, Filter } from 'lucide-react'
import { AppShell } from '@/components/shell/app-shell'
import { PageHeader } from '@/components/ui/page-header'
import { Card, CardHeader, CardBody } from '@/components/ui/card'
import { SeverityBadge, Badge } from '@/components/ui/badge'
import { Spinner, ErrorState, EmptyState } from '@/components/ui/state'
import { useWaterAlerts, useWaterRegions, useAcknowledgeWaterAlert, useResolveWaterAlert } from '@/features/water/hooks'
import { regionNameById, sortBySeverity } from '@/features/water/mappers'
import { fmtNumber, fmtDate, fmtDateTime, fmtPct, timeAgo } from '@/lib/format'
import { useAuth } from '@/context/AuthContext'
import { PERMISSIONS } from '@/lib/permissions'
import type { AlertVM } from '@/features/water/types'

type StatusFilter = 'All' | 'New' | 'Acknowledged' | 'Resolved'

const FILTERS: StatusFilter[] = ['All', 'New', 'Acknowledged', 'Resolved']

export default function AlertsPage() {
  const [filter, setFilter] = useState<StatusFilter>('All')
  const { hasPermission } = useAuth()
  const canOperate = hasPermission(PERMISSIONS.AQUAVISION_ACKNOWLEDGE_ALERT)
  const alertsQuery = useWaterAlerts()
  const regionsQuery = useWaterRegions()
  const ack = useAcknowledgeWaterAlert()
  const resolve = useResolveWaterAlert()

  const regions = regionsQuery.data ?? []
  const all = sortBySeverity(alertsQuery.data ?? [])
  const filtered = filter === 'All' ? all : all.filter((a) => a.status === filter)

  const counts = {
    New: all.filter((a) => a.status === 'New').length,
    Acknowledged: all.filter((a) => a.status === 'Acknowledged').length,
    Resolved: all.filter((a) => a.status === 'Resolved').length,
  }

  const anyBusy = ack.isPending || resolve.isPending

  return (
    <AppShell>
      <div className="space-y-6">
        <PageHeader
          title="Water Alerts"
          description="Early-warning events auto-generated by the anomaly/risk pipeline."
          icon={<Bell className="h-6 w-6" />}
          badge={<Badge tone="amber">{counts.New} new</Badge>}
          action={
            <div className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900/60 p-1">
              {FILTERS.map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`rounded-md px-3 py-1 text-xs font-medium transition-colors ${
                    filter === f ? 'bg-sky-500/15 text-sky-300' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {f === 'All' ? `All (${all.length})` : `${f} (${counts[f as Exclude<StatusFilter, 'All'>]})`}
                </button>
              ))}
            </div>
          }
        />

        <Card>
          <CardHeader
            title={`Alert Queue · ${filter}`}
            subtitle="Click ack to confirm, resolve to close."
            icon={<AlertTriangle className="h-5 w-5" />}
            accent="bg-amber-500/10 text-amber-300"
          />
          <CardBody className="p-0">
            {alertsQuery.isPending ? (
              <div className="p-8"><Spinner /></div>
            ) : alertsQuery.isError ? (
              <div className="p-8"><ErrorState onRetry={() => alertsQuery.refetch()} /></div>
            ) : filtered.length === 0 ? (
              <div className="p-8"><EmptyState title="No alerts in this view" message="Try another filter." /></div>
            ) : (
              <div className="divide-y divide-slate-800/70">
                {filtered.map((alert) => (
                  <AlertRow
                    key={alert.id}
                    alert={alert}
                    regionName={regionNameById(regions, alert.regionId)}
                    busy={anyBusy}
                    canOperate={canOperate}
                    onAck={(notes) => ack.mutate({ alertId: alert.id, notes })}
                    onResolve={(notes) => resolve.mutate({ alertId: alert.id, notes })}
                  />
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      </div>
    </AppShell>
  )
}

function AlertRow({
  alert,
  regionName,
  busy,
  canOperate,
  onAck,
  onResolve,
}: {
  alert: AlertVM
  regionName: string
  busy: boolean
  canOperate: boolean
  onAck: (notes?: string) => void
  onResolve: (notes?: string) => void
}) {
  const [notes, setNotes] = useState('')
  const resolved = alert.status === 'Resolved'
  const acknowledged = alert.status === 'Acknowledged'

  return (
    <div className="p-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <p className="font-mono text-xs text-slate-500">#{alert.id}</p>
            <SeverityBadge severity={alert.severity} />
            <Badge tone={resolved ? 'emerald' : acknowledged ? 'sky' : 'amber'}>{alert.status}</Badge>
          </div>
          <h3 className="mt-2 text-base font-semibold text-slate-100">{alert.alertType}</h3>
          <p className="mt-0.5 text-xs text-slate-500">
            {regionName} · week {fmtDate(alert.weekStartDate)} · created {timeAgo(alert.createdAt)}
          </p>
          <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-400">
            {alert.waiScore != null && <Metric label="WAI" value={fmtNumber(alert.waiScore)} />}
            {alert.rainfallAnomaly != null && <Metric label="Rain anomaly" value={fmtPct(alert.rainfallAnomaly)} />}
            {alert.etAnomaly != null && <Metric label="ET anomaly" value={fmtPct(alert.etAnomaly)} />}
            {alert.surfaceWaterChangePct != null && <Metric label="Δ surface water" value={fmtPct(alert.surfaceWaterChangePct)} />}
          </div>
          {alert.notes && (
            <p className="mt-2 rounded-lg bg-slate-950/60 px-3 py-1.5 font-mono text-[11px] text-slate-500">{alert.notes}</p>
          )}
          {(alert.acknowledgedAt || alert.resolvedAt) && (
            <p className="mt-1.5 text-[11px] text-slate-600">
              {alert.acknowledgedAt && `acked ${fmtDateTime(alert.acknowledgedAt)}`}
              {alert.acknowledgedAt && alert.resolvedAt && ' · '}
              {alert.resolvedAt && `resolved ${fmtDateTime(alert.resolvedAt)}`}
            </p>
          )}
        </div>

        <div className="flex shrink-0 flex-col gap-2">
          {!resolved && canOperate && (
            <>
              <input
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Optional note…"
                className="rounded-lg border border-slate-800 bg-slate-950/60 px-3 py-2 text-xs text-slate-300 placeholder:text-slate-600 focus:border-sky-500/50 focus:outline-none"
              />
              {!acknowledged && (
                <button
                  onClick={() => onAck(notes || undefined)}
                  disabled={busy}
                  className="flex items-center justify-center gap-2 rounded-lg border border-sky-500/30 bg-sky-500/10 px-3 py-2 text-xs font-medium text-sky-300 transition-colors hover:bg-sky-500/20 disabled:opacity-50"
                >
                  <CheckCircle2 className="h-4 w-4" /> Acknowledge
                </button>
              )}
              <button
                onClick={() => onResolve(notes || undefined)}
                disabled={busy}
                className="flex items-center justify-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-xs font-medium text-emerald-300 transition-colors hover:bg-emerald-500/20 disabled:opacity-50"
              >
                <CheckCircle2 className="h-4 w-4" /> Resolve
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <span>
      <span className="text-slate-600">{label}: </span>
      <span className="font-semibold text-slate-200">{value}</span>
    </span>
  )
}